### ISSUE TITLE
module 'collections' has no attribute 'Mapping' on Python 3.10

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/nmrml2isa#4]
Hi,
for nmrml2isa-0.3.1 on python 3.10 I get the following exception:
```
~/.local/bin/nmrml2isa -h
Traceback (most recent call last):
  File "/home/sneumann/.local/bin/nmrml2isa", line 5, in <module>
    from nmrml2isa.parsing import run
  File "/home/sneumann/.local/lib/python3.10/site-packages/nmrml2isa/parsing.py", line 51, in <module>
    from .isa   import ISA_Tab
  File "/home/sneumann/.local/lib/python3.10/site-packages/nmrml2isa/isa.py", line 14, in <module>
    from .utils import ChainMap, PermissiveFormatter
  File "/home/sneumann/.local/lib/python3.10/site-packages/nmrml2isa/utils.py", line 68, in <module>
    class ChainMap(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Comment by althonos** [comment]
Hi @sneumann,
I pushed a version with a fix, this took a bit longer because I also needed to rewrite the CI to use GitHub Actions since Travis-CI is not free anymore.
